spring.application.name=gestions_des_consultations_cliniques
#spring.datasource.url=jdbc:mysql://localhost:3306/DB_CABINET
spring.datasource.url=jdbc:mysql://localhost:3306/consultation_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.port=8080